// generated by newgenasym  Mon May 30 21:21:18 2011


module \54ac16245_v1  (\1a1 , \1a2 , \1a3 , \1a4 , \1a5 , \1a6 , \1a7 , \1a8 , \1b1 , \1b2 , \1b3 , \1b4 , \1b5 ,
        \1b6 , \1b7 , \1b8 , \1dir , \1oe* , \2a1 , \2a2 , \2a3 , \2a4 , \2a5 , \2a6 , \2a7 , \2a8 ,
        \2b1 , \2b2 , \2b3 , \2b4 , \2b5 , \2b6 , \2b7 , \2b8 , \2dir , \2oe* , gnd10, gnd15,
        gnd21, gnd28, gnd34, gnd39, gnd4, gnd45, vcca31, vcca42,
        vccb18, vccb7);
    inout \1a1 ;
    inout \1a2 ;
    inout \1a3 ;
    inout \1a4 ;
    inout \1a5 ;
    inout \1a6 ;
    inout \1a7 ;
    inout \1a8 ;
    inout \1b1 ;
    inout \1b2 ;
    inout \1b3 ;
    inout \1b4 ;
    inout \1b5 ;
    inout \1b6 ;
    inout \1b7 ;
    inout \1b8 ;
    input \1dir ;
    input \1oe* ;
    inout \2a1 ;
    inout \2a2 ;
    inout \2a3 ;
    inout \2a4 ;
    inout \2a5 ;
    inout \2a6 ;
    inout \2a7 ;
    inout \2a8 ;
    inout \2b1 ;
    inout \2b2 ;
    inout \2b3 ;
    inout \2b4 ;
    inout \2b5 ;
    inout \2b6 ;
    inout \2b7 ;
    inout \2b8 ;
    input \2dir ;
    input \2oe* ;
    input gnd10;
    input gnd15;
    input gnd21;
    input gnd28;
    input gnd34;
    input gnd39;
    input gnd4;
    input gnd45;
    input vcca31;
    input vcca42;
    input vccb18;
    input vccb7;


    initial
        begin
        end

endmodule
