// generated by newgenasym  Sun Jun 10 09:17:20 2007


module ac_hc_74_v1 (clk, clr, d, pre, q, \q* );
    parameter    size = 1;
    input [size-1:0] clk;
    input [size-1:0] clr;
    input [size-1:0] d;
    input [size-1:0] pre;
    output [size-1:0] q;
    output [size-1:0] \q* ;


    initial
        begin
        end

endmodule
