-- generated by newgenasym Sun Jun 10 09:17:20 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ac_hc_74_v1 is
    generic (
        size:positive:= 1
            );
    port (    
	CLK:       IN     STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	CLR:       IN     STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	D:         IN     STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	PRE:       IN     STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	Q:         OUT    STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	\q*\:      OUT    STD_LOGIC_VECTOR (size-1 DOWNTO 0));
end ac_hc_74_v1;
