// generated by newgenasym  Sun Jun 10 08:44:13 2007


module ac_hc_04_v1 (a, \o* );
    parameter    size = 1;
    input [size-1:0] a;
    output [size-1:0] \o* ;


    initial
        begin
        end

endmodule
