// generated by newgenasym  Sun Jun 10 11:48:51 2007


module ac_hc_08_v1 (a, b, o);
    parameter    size = 1;
    input [size-1:0] a;
    input [size-1:0] b;
    output [size-1:0] o;


    initial
        begin
        end

endmodule
